spring: 
  datasources:  
      - datasource_name: DEFAULT ##数据源bean的名称
        url: jdbc:mysql://localhost:3306/db1?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
      - datasource_name: DB2
        url: jdbc:mysql://localhost:3306/db2?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
  mongodb:
    infos: 
      - url:  mongodb://dev_labor:KPmaqdeVs9x7QWtcXHyq@dev.mongodb1.cnhz.shishike.com:3717,dev.mongodb2.cnhz.shishike.com:3717/labor_dev?replicaSet=mgset-1033621
        templateName: mongoTemplate1 ##mongoTemplate bean的名称
      - url:  mongodb://dev_labor:KPmaqdeVs9x7QWtcXHyq@dev.mongodb1.cnhz.shishike.com:3717,dev.mongodb2.cnhz.shishike.com:3717/labor_dev?replicaSet=mgset-1033621
        templateName: mongoTemplate2 
